export const Menu = [
  [
    {
      name: '炸酱面(小/大)',
      nameKr: '짜장면(小/大)',
      price: '￥20/25',
      type: 'noodle',
    },
    {
      name: '干炸酱面(小/大)',
      nameKr: '간짜장(小/大)',
      price: '￥25/30',
      type: 'noodle',
    },
    {
      name: '三鲜炸酱面(小/大)',
      nameKr: '삼선짜장(小/大)',
      price: '￥30/35',
      type: 'noodle',
    },
    {
      name: '火辣炸酱面(小/大)',
      nameKr: '불짜장(小/大)',
      price: '￥30/35',
      type: 'noodle',
    },
    {
      name: '四川炸酱面(小/大)',
      nameKr: '사천짜장(小/大)',
      price: '￥25/30',
      type: 'noodle',
    },
    {
      name: '百年炸酱面(小/大)',
      nameKr: '백년짜장(小/大)',
      price: '￥30/35',
      type: 'noodle',
    },
    {
      name: '盘子炸酱面(小/大)',
      nameKr: '쟁반짜장(小/大)',
      price: '￥30/50',
      type: 'noodle',
    },
    {
      name: '盘子炸酱面(小/大)',
      nameKr: '쟁반짜장(小/大)',
      price: '￥30/50',
      type: 'noodle',
    },
    {
      name: '炒码面(小/大)',
      nameKr: '짬뽕(小/大)',
      price: '￥25/30',
      type: 'noodle',
    },
    {
      name: '三鲜炒码面(小/大)',
      nameKr: '삼선짬뽕(小/大)',
      price: '￥30/35',
      type: 'noodle',
    },
    {
      name: '海虹炒码面(小/大)',
      nameKr: '홍합짬뽕(小/大)',
      price: '￥30/35',
      type: 'noodle',
    },
    {
      name: '海鲜火辣汤面(小/大)',
      nameKr: '고추짬뽕(小/大)',
      price: '￥35/40',
      type: 'noodle',
    },
    {
      name: '白炒码面(小/大)',
      nameKr: '백짬뽕(小/大)',
      price: '￥25/30',
      type: 'noodle',
    },
    {
      name: '无汤炒码面(小/大)',
      nameKr: '볶음짬뽕(小/大)',
      price: '￥30/50',
      type: 'noodle',
    },
  ],

  //料理
  [
    {
      name: '糖醋肉(小/大)',
      nameKr: '탕수육(小/大)',
      price: '￥45/70',
      type: 'main',
    },
    {
      name: '炒肉两张皮',
      nameKr: '양장피',
      price: '￥50',
      type: 'main',
    },
    {
      name: '八宝菜',
      nameKr: '팔보채',
      price: '￥60',
      type: 'main',
    },
    {
      name: '杂菜',
      nameKr: '잡채',
      price: '￥30',
      type: 'main',
    },
    {
      name: '青椒杂菜',
      nameKr: '고추잡채',
      price: '￥40',
      type: 'main',
    },
    {
      name: '杂拌菜',
      nameKr: '잡탕',
      price: '￥60',
      type: 'main',
    },
    {
      name: '干烹鸡',
      nameKr: '깐풍기',
      price: '￥50',
      type: 'main',
    },
    {
      name: '辣椒鸡',
      nameKr: '라조기',
      price: '￥50',
      type: 'main',
    },
    {
      name: '流三丝',
      nameKr: '유산슬',
      price: '￥50',
      type: 'main',
    },
    {
      name: '干烹虾仁',
      nameKr: '깐풍새우',
      price: '￥60',
      type: 'main',
    },
    {
      name: '干烧虾仁',
      nameKr: '깐쇼새우',
      price: '￥60',
      type: 'main',
    },
    {
      name: '南煎丸子',
      nameKr: '난자완스',
      price: '￥60',
      type: 'main',
    },
    {
      name: '麻婆豆腐',
      nameKr: '마파두부',
      price: '￥30',
      type: 'main',
    },
    {
      name: '凉拌蜇皮',
      nameKr: '해파리냉채',
      price: '￥40',
      type: 'main',
    },
    {
      name: '炒海参',
      nameKr: '해삼탕',
      price: '￥100',
      type: 'main',
    },
    {
      name: '海参肉片',
      nameKr: '해삼쥬스',
      price: '￥100',
      type: 'main',
    },
    {
      name: '四川辣椒鸡',
      nameKr: '사천라조기',
      price: '￥50',
      type: 'main',
    },
    {
      name: '炸鱿鱼',
      nameKr: '오징어튀김',
      price: '￥40',
      type: 'main',
    },
    {
      name: '原味炸鸡',
      nameKr: '치킨볼',
      price: '￥50',
      type: 'main',
    },
    {
      name: '韭菜杂菜',
      nameKr: '부추잡채',
      price: '￥40',
      type: 'main',
    },
    {
      name: '三鲜鸡蛋汤',
      nameKr: '삼선계란탕',
      price: '￥30',
      type: 'main',
    },
    {
      name: '三鲜锅巴汤',
      nameKr: '해물누릉지탕',
      price: '￥40',
      type: 'main',
    },
    {
      name: '海鲜辣汤',
      nameKr: '안주짬뽕탕',
      price: '￥30',
      type: 'main',
    },
  ],
  [
    {
      name: '炸酱饭',
      nameKr: '짜장밥',
      price: '￥25',
      type: 'rice',
    },
    {
      name: '炒码饭',
      nameKr: '짬뽕밥',
      price: '￥25',
      type: 'rice',
    },
    {
      name: '炒饭',
      nameKr: '볶음밥',
      price: '￥25',
      type: 'rice',
    },
    {
      name: '三鲜炒饭',
      nameKr: '삼선볶음밥',
      price: '￥30',
      type: 'rice',
    },
    {
      name: '虾仁炒饭',
      nameKr: '새우볶음밥',
      price: '￥25',
      type: 'rice',
    },
    {
      name: '辣白菜炒饭',
      nameKr: '김치볶음밥',
      price: '￥25',
      type: 'rice',
    },
    {
      name: '三鲜炒饭',
      nameKr: '삼선볶음밥',
      price: '￥25',
      type: 'rice',
    },
  ],
];
